### ISSUE TITLE
libvoikko violates C++ ODR rule making it fail to compile witih LTO

### ISSUE THREAD

**Issue by aleasto** [voikko/corevoikko#62]
The public header `voikko.h` declares some opaque data types, such as `struct VoikkoGrammarError`, `struct VoikkoHandle`, `struct voikko_mor_analysis`.

In the implementations however, the type names are under namespaces, or even use different names.

Here's one example error from gcc 14.2.0 and `CXXFLAGS="-flto=auto"`:
```
./voikko.h:309:6: error: 'voikkoFreeGrammarError' violates the C++ One Definition Rule [-Werror=odr]
  309 | void voikkoFreeGrammarError(struct VoikkoGrammarError * error);
      |      ^
grammar/interface.cpp:116:19: note: type mismatch in parameter 1
  116 | VOIKKOEXPORT void voikkoFreeGrammarError(VoikkoGrammarError * error) {
      |                   ^
./grammar/VoikkoGrammarError.hpp:40:7: note: type name 'libvoikko::grammar::VoikkoGrammarError' should match type name 'VoikkoGrammarError'
   40 | class VoikkoGrammarError {
      |       ^
./voikko.h:242:8: note: the incompatible type is defined here
  242 | struct VoikkoGrammarError;
      |        ^
grammar/interface.cpp:116:19: note: 'voikkoFreeGrammarError' was previously declared here
  116 | VOIKKOEXPORT void voikkoFreeGrammarError(VoikkoGrammarError * error) {
      |                   ^
```

**Comment by ahomansikka** [comment]
It seems they have changed the compiler. It works on gcc version 13.3.0.


pe, 2025-03-28 kello 05:11 -0700, Alessandro Astone kirjoitti:

**Comment by hatapitk** [comment]
Thanks for the report! This was due to history of the project: originally C, then internally converted to C++ while keeping the external API/ABI in plain C (easier to call the functions from Java, Python etc. when there is no name mangling). I renamed the internal names of these few types which made the code prettier in some places, uglier in others. But seems like LTO is working now.
